fix ID

diff --git a/.github/workflows/mlflow-ci.yml b/.github/workflows/mlflow-ci.yml
--- a/.github/workflows/mlflow-ci.yml
+++ b/.github/workflows/mlflow-ci.yml
@@ -45,10 +45,15 @@ jobs:
       - name: 🔍 Get Run ID
         id: get_run_id
         run: |
-          RUN_ID=$(mlflow runs list --experiment-name "Soil_Classification_CI" | awk 'NR==2 {print $1}')
+          EXPERIMENT_ID=$(mlflow experiments list | awk -F' ' '$2=="Soil_Classification_CI"{print $1}')
+          if [ -z "$EXPERIMENT_ID" ]; then
+            echo "::error::Experiment not found"
+            exit 1
+          fi
+          RUN_ID=$(mlflow runs list --experiment-id "$EXPERIMENT_ID" | awk 'NR==2 {print $1}')
           if [ -z "$RUN_ID" ]; then
             echo "::error::No MLflow runs found"
-          exit 1
+            exit 1
           fi
           echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
           echo "Model Run ID: $RUN_ID"
